// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5L_2xkDONpP-VghHhnAGTX00yQCWH_K4',
    appId: '1:988130211442:web:03b1152cb60a976aee34eb',
    messagingSenderId: '988130211442',
    projectId: 'breeze-food-4336f',
    authDomain: 'breeze-food-4336f.firebaseapp.com',
    storageBucket: 'breeze-food-4336f.firebasestorage.app',
    measurementId: 'G-CT6VPCERSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDuhq3WeBRlCgXMy23r_yWXZLuxUzYzHE',
    appId: '1:988130211442:android:456bdb3966a9f0e5ee34eb',
    messagingSenderId: '988130211442',
    projectId: 'breeze-food-4336f',
    storageBucket: 'breeze-food-4336f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf-t43zY_KBjduV4T7IPRKex2kyxknhX4',
    appId: '1:988130211442:ios:b1e77f0dc6e4252bee34eb',
    messagingSenderId: '988130211442',
    projectId: 'breeze-food-4336f',
    storageBucket: 'breeze-food-4336f.firebasestorage.app',
    iosBundleId: 'com.example.breezefood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf-t43zY_KBjduV4T7IPRKex2kyxknhX4',
    appId: '1:988130211442:ios:b1e77f0dc6e4252bee34eb',
    messagingSenderId: '988130211442',
    projectId: 'breeze-food-4336f',
    storageBucket: 'breeze-food-4336f.firebasestorage.app',
    iosBundleId: 'com.example.breezefood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5L_2xkDONpP-VghHhnAGTX00yQCWH_K4',
    appId: '1:988130211442:web:d626c9d33d6b46d8ee34eb',
    messagingSenderId: '988130211442',
    projectId: 'breeze-food-4336f',
    authDomain: 'breeze-food-4336f.firebaseapp.com',
    storageBucket: 'breeze-food-4336f.firebasestorage.app',
    measurementId: 'G-Y749LZ313C',
  );
}
